name: run wiki bot

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Detect trigger source
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Triggered manually"
            echo "MANUAL_RUN=true" >> $GITHUB_ENV
          else
            echo "Triggered on schedule"
            echo "MANUAL_RUN=false" >> $GITHUB_ENV
          fi
      - name: Run bot
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          MANUAL_RUN: ${{ env.MANUAL_RUN }}
        run: python bot.py
