name: Unzip and Push Wiki Image Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # give write access to repository contents

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip the wiki-image-bot.zip to root
          run: |
           unzip wiki-image-bot.zip
           shopt -s dotglob  # include hidden files
           mv wiki-image-bot/* .
           rmdir wiki-image-bot

      - name: Commit and push the extracted files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
          git add .
          git commit -m "Add wiki-image-bot files"
          git push
